config/routes.rb
Rails.application.routes.draw do

  options = Rails.env.production? ? { path: "", constraints: { subdomain: 'es' }} : {}

  concern :pick do
    member do
      get :pick
      patch :pick, action: :update_pick
    end
  end

  concern :review do
    member do
      get :review
      patch :review, action: :update_review
    end
  end

  namespace :merchants, options do
    resource :merchant_session, path: "session"
    resource :merchant do
      get :forget_password
      match :verification_code, via: [:get, :post, :patch]
      match :confirm, via: [:post, :patch]

      get :password
      patch :password, action: :update_password
    end

    resource :note

    resources :orders, concerns: [:pick, :review] do
      resources :bids do
        member do
          get :pick
        end
      end

      resources :numbers

      collection do
        get :"pay/:id", action: :pay, as: :pay
      end

      member do
        post :pend
        post :cancel
        match :refund, via: [:get, :patch]
        match :notify, via: [:get, :post]
        get :result
        post :confirm
        post :rework
        get :revoke
        get :remark
        patch :remark, action: :update_remark
      end
    end

    namespace :hosting do
      resources :orders, concerns: [:pick, :review] do
        resources :partchecks
        member do
          match :refund, via: [:get, :patch]
          post :confirm
          post :rework
          get :revoke
          get :remark
          patch :remark, action: :update_remark
          get :procedure_price
          patch :procedure_price, action: :update_procedure_price
          get :emergency
          get :unemergency
          post :confirmwithdrawal
          get :service_staff
        end
        collection do
          get 'automatic'
          get 'automatic_pop'
        end
      end
      resources :numbers
      resources :partchecks
    end

    resources :merchants
    resources :mechanics do
      member do
        post :follow
        post :unfollow
        get :remark
        patch :remark, action: :update_remark
        get :reviews
        get :"skills/:skill", action: :skill, as: :skill
      end
    end

    namespace :admin do
      resources :merchants do
        member do
          post :active
          post :inactive
        end
      end
      resources :orders do
        member do
          post :close
        end
      end
      resource :store
      resources :recharges do
        member do
          match :notify, via: [:get, :post]
          get :result
        end
      end
    end

    namespace :store do
      resources :orders
    end
    resource :store

    root to: "orders#new"
  end

  mount WeixinRailsMiddleware::Engine, at: "/"
  resource :user do
      member do
        get :photo
        patch :update_photo
        get :holiday
        patch :update_holiday
      end
    end
  resource :user_session, path: "session" do
    post :verification_code
  end
  resource :user_group do
    get :weixin_qr_code
    get :users
  end
  resources :mechanics do
    member do
      get :follow
      get :unfollow
      get :reviews
    end
  end

  resources :orders, concerns: [:review] do
    resources :bids do
      member do
        get :pick
      end
    end

    collection do
      get :"pay/:id", action: :pay, as: :pay
      get :not_found
    end

    member do
      get :cancel
      get :refund
      post :notify
      get :result
      get :work
      patch :finish
      get :confirm
    end
  end

  resources :withdrawals

  namespace :admin do
    concern :confirm do
      collection do
        get :confirmed
      end
      member do
        post :confirm
      end
    end
    concern :confirm_nopay do
      collection do
        get :confirm_nopayed
      end
      member do
        post :confirm_nopay
      end
    end
    concern :message do
      member do
        post :message
      end
    end
    concern :cancel do
      collection do
        get :canceled
      end
      member do
        post :cancel
      end
    end
    concern :hide do
      collection do
        get :hidden
      end
      member do
        post :hide
        post :unhide
      end
    end
    concern :freeze do
      collection do
        get :frozen
      end
      member do
        post :freeze
      end
    end
    concern :hidereg do
      collection do
        get :reg
      end
      member do
        post :hidereg
      end
    end
    concern :hideupdate do
      collection do
        get :userupdate
      end
      member do
        post :hideupdate
      end
    end

    resource :administrator_session, path: "session"
    resource :administrator, only: [] do
      get :forget_password
      match :verification_code, via: [:get, :post, :patch]
      match :confirm, via: [:post, :patch]

      get :password
      patch :password, action: :update_password
    end

    resources :administrators do
      member do
        post :active
        post :inactive
      end
    end

    resources :users do
      member do
        post :mechanicize

        get :balance,:clear_weixin,:clear_withdrawal_weixin
        patch :balance, action: :update_balance
      end
    end
    resources :user_groups, concerns: [:confirm]
    resources :mechanics, concerns: [:hide,:hidereg,:hideupdate] do
      resources :orders
      resources :metrics
      collection do
        get :import
        post :import, action: :create_import
      end

      member do
        post :clientize
      end
    end
    resources :merchants, concerns: [:confirm] do
      resources :orders
      resources :metrics
      member do
        post :active
        post :inactive
        get :settings
        post :settings, action: :update_settings
        get :product
        patch :product, action: :update_product
      end
    end
    resources :orders
    resources :metrics
    resources :refunds, concerns: [:confirm, :freeze]
    resources :withdrawals, concerns: [:confirm, :cancel, :confirm_nopay, :message] do
      collection do
        get :settings
        post :settings, action: :update_settings
      end
    end
    namespace :settings do
      resources :skills
      resources :brands
      resources :series, except: :show
    end
    namespace :reports do
      resources :provinces
      resources :finishedprovinces
      resources :dayreports
      resources :profits
      resources :partchecks
    end

    root to: "users#index"
  end

  root to: "users#show"
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  has_many :users
  has_many :orders, through: :users

  has_many :mechanics, through: :users, source: :mechanic
  has_many :mechanic_orders, through: :mechanics, source: :orders

  validates_presence_of :nickname

  delegate :nickname, :role, to: :user, prefix: true, allow_nil: true

  scope :confirmeds, -> { where(confirmed: true) }
  scope :unconfirmeds, -> { where.not(confirmed: true) }

  def increase_total_commission! amount
    increment!(:total_commission, amount)
  end

  def confirm!
    update_attribute(:confirmed, true)
  end

  def settled_orders_count
    orders.settleds.count + mechanic_orders.settleds.count
  end

  def users_count
    users.count
  end

  def weixin_qr_code_url
    unless weixin_qr_code_ticket
      ticket = Weixin.create_qr_limit_str_scene(scene_str: "user_group_#{id}").result["ticket"]
      if ticket
        update_attribute(:weixin_qr_code_ticket, ticket)
      else
        return nil
      end
    end

    Weixin.qr_code_url(weixin_qr_code_ticket)
  end

end

app/controllers/admin/user_groups_controller.rb
class Admin::UserGroupsController < Admin::ApplicationController
  before_action :find_user_group, except: [ :index, :confirmed ]

  def index
    @user_groups = UserGroup.unconfirmeds
  end

  def confirmed
    @user_groups = UserGroup.confirmeds
    render :index
  end

  def confirm
    @user_group.confirm!
    redirect_to_referer!
  end

  def destroy
    @user_group.destroy
    redirect_to_referer!
  end

  private

    def find_user_group
      @user_group = UserGroup.find(params[:id])
    end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController

  def new
    @user_group = user_group_klass.first || user_group_klass.new
    flash.now[:notice] = "堂主申请正在审核中..." if @user_group.persisted?
  end

  def create
    @user_group = user_group_klass.new(user_group_params)
    if @user_group.save
      redirect_to user_path
    else
      render :new
    end
  end

  def update
    @user_group = user_group_klass.first
    if @user_group.update_attributes(user_group_params)
      redirect_to user_path
    else
      render :new
    end
  end

  def show
    @user_group = user_group_klass.first
    redirect_to user_path unless @user_group
  end

  private

    def user_group_klass
      UserGroup.where(user_id: current_user)
    end

    def user_group_params
      params.require(:user_group).permit(:nickname, :description)
    end
end

app/views/user_groups/new.html.erb
<%= content_for :title do %>
  申请堂主
<% end %>

<%= simple_form_for(@user_group, url: user_group_path) do |f| %>
  <%= f.error_messages %>

  <div class="content-padded margin-top-large">
    <%= f.input :nickname %>
    <%= f.input :description, input_html: { rows: 4 } %>

    <%= f.button :submit, "提交申请", class: "btn-block btn-positive" %>
  </div>
<% end %>

app/views/user_groups/show.html.erb
<%= content_for :title do %>
  我的分堂
<% end %>

<div class="content-padded">
  <h3 class="text-center"><%= @user_group.nickname %></h3>
</div>

<div class="hero segmented-items segmented-items-bordered text-center">
  <div class="item">
    <h2><%= number_with_delimiter(@user_group.settled_orders_count) %></h2>
    <p>分堂业绩（笔）</p>
  </div>
  <div class="item">
    <h2><%= number_with_delimiter(@user_group.total_commission) %></h2>
    <p>分堂佣金</p>
  </div>
</div>

<ul class="table-view">
  <li class="table-view-cell">
    <%= link_to "分享二维码", weixin_qr_code_user_group_path, class: "navigate-right" %>
  </li>
  <li class="table-view-cell">
    <%= link_to "分堂成员", users_user_group_path, class: "navigate-right" %>
  </li>
</ul>

app/views/user_groups/users.html.erb
<%= content_for :title do %>
  分堂成员
<% end %>

<% user_group = current_user.owner_user_group %>
<% users = user_group.users %>

<ul class="table-view">
  <li class="table-view-cell media">
    <%= image_tag user_group.user.avatar.url(:thumb), class: "media-object pull-left" %>
    <div class="media-body">
      <div class="media-block">
        <%= user_group.user.nickname %>
        <div class="btn btn-mini btn-primary">堂主</div>
      </div>
      <% if user_group.user.mechanic? %>
        <div class="media-block">
          <p class="pull-right">接单 <%= user_group.user.mechanic.available_orders_count %> 次</p>
          <p>专业 <%= user_group.user.mechanic.professionality_average %> 分 守时 <%= user_group.user.mechanic.timeliness_average %> 分</p>
        </div>
      <% end %>
    </div>
  </li>
  <% users.each do |user| %>
    <li class="table-view-cell media">
      <%= image_tag user.avatar.url(:thumb), class: "media-object pull-left" %>
      <div class="media-body">
        <div class="media-block">
          <%= user.nickname %>
        </div>
        <% if user.mechanic? %>
          <div class="media-block">
            <p class="pull-right">接单 <%= user.mechanic.available_orders_count %> 次</p>
            <p>专业 <%= user.mechanic.professionality_average %> 分 守时 <%= user.mechanic.timeliness_average %> 分</p>
          </div>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/user_groups/weixin_qr_code.html.erb
<%= content_for :title do %>
  乐享有车生活、汽车堂邀你加入！
<% end %>

<%= image_tag current_user.owner_user_group.weixin_qr_code_url, id: "qr_code" %>