config/routes.rb
Rails.application.routes.draw do

  options = Rails.env.production? ? { path: "", constraints: { subdomain: 'es' }} : {}

  concern :pick do
    member do
      get :pick
      patch :pick, action: :update_pick
    end
  end

  concern :review do
    member do
      get :review
      patch :review, action: :update_review
    end
  end

  namespace :merchants, options do
    resource :merchant_session, path: "session"
    resource :merchant do
      get :forget_password
      match :verification_code, via: [:get, :post, :patch]
      match :confirm, via: [:post, :patch]

      get :password
      patch :password, action: :update_password
    end

    resource :note

    resources :orders, concerns: [:pick, :review] do
      resources :bids do
        member do
          get :pick
        end
      end

      resources :numbers

      collection do
        get :"pay/:id", action: :pay, as: :pay
      end

      member do
        post :pend
        post :cancel
        match :refund, via: [:get, :patch]
        match :notify, via: [:get, :post]
        get :result
        post :confirm
        post :rework
        get :revoke
        get :remark
        patch :remark, action: :update_remark
      end
    end

    namespace :hosting do
      resources :orders, concerns: [:pick, :review] do
        resources :partchecks
        member do
          match :refund, via: [:get, :patch]
          post :confirm
          post :rework
          get :revoke
          get :remark
          patch :remark, action: :update_remark
          get :procedure_price
          patch :procedure_price, action: :update_procedure_price
          get :emergency
          get :unemergency
          post :confirmwithdrawal
          get :service_staff
        end
        collection do
          get 'automatic'
          get 'automatic_pop'
        end
      end
      resources :numbers
      resources :partchecks
    end

    resources :merchants
    resources :mechanics do
      member do
        post :follow
        post :unfollow
        get :remark
        patch :remark, action: :update_remark
        get :reviews
        get :"skills/:skill", action: :skill, as: :skill
      end
    end

    namespace :admin do
      resources :merchants do
        member do
          post :active
          post :inactive
        end
      end
      resources :orders do
        member do
          post :close
        end
      end
      resource :store
      resources :recharges do
        member do
          match :notify, via: [:get, :post]
          get :result
        end
      end
    end

    namespace :store do
      resources :orders
    end
    resource :store

    root to: "orders#new"
  end

  mount WeixinRailsMiddleware::Engine, at: "/"
  resource :user do
      member do
        get :photo
        patch :update_photo
        get :holiday
        patch :update_holiday
      end
    end
  resource :user_session, path: "session" do
    post :verification_code
  end
  resource :user_group do
    get :weixin_qr_code
    get :users
  end
  resources :mechanics do
    member do
      get :follow
      get :unfollow
      get :reviews
    end
  end

  resources :orders, concerns: [:review] do
    resources :bids do
      member do
        get :pick
      end
    end

    collection do
      get :"pay/:id", action: :pay, as: :pay
      get :not_found
    end

    member do
      get :cancel
      get :refund
      post :notify
      get :result
      get :work
      patch :finish
      get :confirm
    end
  end

  resources :withdrawals

  namespace :admin do
    concern :confirm do
      collection do
        get :confirmed
      end
      member do
        post :confirm
      end
    end
    concern :confirm_nopay do
      collection do
        get :confirm_nopayed
      end
      member do
        post :confirm_nopay
      end
    end
    concern :message do
      member do
        post :message
      end
    end
    concern :cancel do
      collection do
        get :canceled
      end
      member do
        post :cancel
      end
    end
    concern :hide do
      collection do
        get :hidden
      end
      member do
        post :hide
        post :unhide
      end
    end
    concern :freeze do
      collection do
        get :frozen
      end
      member do
        post :freeze
      end
    end
    concern :hidereg do
      collection do
        get :reg
      end
      member do
        post :hidereg
      end
    end
    concern :hideupdate do
      collection do
        get :userupdate
      end
      member do
        post :hideupdate
      end
    end

    resource :administrator_session, path: "session"
    resource :administrator, only: [] do
      get :forget_password
      match :verification_code, via: [:get, :post, :patch]
      match :confirm, via: [:post, :patch]

      get :password
      patch :password, action: :update_password
    end

    resources :administrators do
      member do
        post :active
        post :inactive
      end
    end

    resources :users do
      member do
        post :mechanicize

        get :balance,:clear_weixin,:clear_withdrawal_weixin
        patch :balance, action: :update_balance
      end
    end
    resources :user_groups, concerns: [:confirm]
    resources :mechanics, concerns: [:hide,:hidereg,:hideupdate] do
      resources :orders
      resources :metrics
      collection do
        get :import
        post :import, action: :create_import
      end

      member do
        post :clientize
      end
    end
    resources :merchants, concerns: [:confirm] do
      resources :orders
      resources :metrics
      member do
        post :active
        post :inactive
        get :settings
        post :settings, action: :update_settings
        get :product
        patch :product, action: :update_product
      end
    end
    resources :orders
    resources :metrics
    resources :refunds, concerns: [:confirm, :freeze]
    resources :withdrawals, concerns: [:confirm, :cancel, :confirm_nopay, :message] do
      collection do
        get :settings
        post :settings, action: :update_settings
      end
    end
    namespace :settings do
      resources :skills
      resources :brands
      resources :series, except: :show
    end
    namespace :reports do
      resources :provinces
      resources :finishedprovinces
      resources :dayreports
      resources :profits
      resources :partchecks
    end

    root to: "users#index"
  end

  root to: "users#show"
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  before_action :find_order, except: [ :index ]

  def index
    @orders = if params[:mechanic_id]
        @mechanic = Mechanic.where(user_id: params[:mechanic_id]).first!
        @mechanic.orders
      elsif params[:merchant_id]
        @merchant = Merchant.where(user_id: params[:merchant_id]).first!
        @merchant.orders
      else
        Order.all
      end
  end

  private

    def find_order
      @order = Order.find(params[:id])
    end
end

app/controllers/merchants/admin/orders_controller.rb
class Merchants::Admin::OrdersController < Merchants::Admin::ApplicationController
  before_action :find_order, except: [ :index ]

  def index
    @state = if %w(pendeds paids workings settleds refundeds revieweds closeds).include? params[:state]
        params[:state].to_sym
      else
        :pendeds
      end
    @orders = order_klass.send(@state)
  end

  def close
    @order.close!
    flash[:notice] = "订单标记为已结算！"
    redirect_to current_order_path
  end

  private

    def current_order_path
      merchants_admin_order_path(@order)
    end

    def find_order
      @order = order_klass.find(params[:id])
    end

    def order_klass
      Order.where(user_id: current_store)
    end
end

app/controllers/merchants/hosting/orders_controller.rb
class Merchants::Hosting::OrdersController < Merchants::OrdersController
  before_action :redirect_user
  before_action :redirect_user_dispatcher, only: [ :confirm, :confirmwithdrawal ]
  skip_before_action :redirect_user, only: [:automatic, :automatic_pop]
  skip_before_action :redirect_user_dispatcher, only: [:automatic, :automatic_pop]
  skip_before_action :authenticate!, only: [:automatic, :automatic_pop]
  before_action :find_order, except: [ :index, :new, :create, :notify, :not_found , :automatic, :automatic_pop]


  def index
    @state = if %w(unassigneds assigneds workings confirmings finisheds unfinisheds settleds emergencys finished_all_nochecks finished_part_nochecks unfinished_all_checks unfinished_part_checks).include? params[:state]
        params[:state].to_sym
      else
        :unassigneds
      end
    
    @orders = order_klass.send(@state)
  end
  


  def update_pick
    mechanic_id = params[:order][:mechanic_id]
    if mechanic_id.present?
      remark = params[:order][:remark]
      pre_remark = params[:order][:pre_remark]
      remark = pre_remark if pre_remark
      @order.update_attribute(:remark, remark) if remark
      procedure_price = params[:order][:pre_procedure_price]
      if(procedure_price.present?)
        if procedure_price.to_i > @order.quoted_price
        @order.errors.add(:pre_procedure_price, "应低于订单标价")
        render :show
        return 
        end
      end
      @order.update_attribute(:procedure_price, procedure_price) if procedure_price
      mechanic = Mechanic.find(mechanic_id)
      @order.repick! mechanic,current_merchant.id,current_merchant.nickname
      redirect_to current_order_path
    else
      @order.remark = params[:order][:remark]
      @order.errors.add :base, "请选择一个技师"
      render :pick
    end
  end

  def update_procedure_price
    if @order.update_attributes(procedure_price_order_params)
      redirect_to current_order_path
    else
      render :procedure_price
    end
  end

  def automatic
    Order.hostings.unassigneds.where("(skill_cd=28 or skill_cd=29 or skill_cd=42 or skill_cd=9 or skill_cd=34 or skill_cd=44 or skill_cd=146) and automatic_repick_check=false").each do |unassigned_order_klass|
       unassigned_order_klass_order=Order.find(unassigned_order_klass.id)
       unassigned_order_klass_order.automatic_repick!
       unassigned_order_klass_order.update_attribute(:automatic_repick_check,true)
    end 
    Order.hostings.confirmings.where("(hosting_remark is null or hosting_remark='') and automatic_confirm_check=false").each do |confirming_order_klass|
       confirming_order_klass_order=Order.find(confirming_order_klass.id)
       confirming_order_klass_order.automatic_confirm!
       confirming_order_klass_order.update_attribute(:automatic_confirm_check,true)
    end 
    #trigger automatic_repick
  end

  def automatic_pop
    Order.hostings.unassigneds.where("(skill_cd=28 or skill_cd=29 or skill_cd=42 or skill_cd=9 or skill_cd=34 or skill_cd=44 or skill_cd=146) and automatic_repick_check=false").each do |unassigned_order_klass|
       unassigned_order_klass_order=Order.find(unassigned_order_klass.id)
       unassigned_order_klass_order.automatic_repick!
    end 
  end  

  def service_staff
    @order.mechanic.update_attribute(:service_staff,params[:service_staff])
    flash[:notice] = "设置微信客服成功"
    redirect_to_referer!
  end

  private

    def current_order_path
      merchants_hosting_order_path(@order)
    end

    def redirect_pending
      ordercount = order_klass.confirmings.count
      if ordercount>0
        flash[:notice] = "您有#{ordercount}条需要确认完工的订单..."
        #redirect_to merchants_hosting_order_path(order)
      end
    end

    def order_klass
      Order.hostings
    end

    def find_order
      @order = order_klass.find(params[:id])
    end

    alias_method :find_store_order, :find_order

    def redirect_user
      unless current_store.host?
        flash[:error] = "无法访问此页面！"
        redirect_to merchants_root_path
      end
    end

    def remark_order_params
      params.require(:order).permit(:hosting_remark)
    end

    def procedure_price_order_params
      params.require(:order).permit(:procedure_price)
    end
end

app/controllers/merchants/store/orders_controller.rb
class Merchants::Store::OrdersController < Merchants::ApplicationController
  before_action :find_order, except: [ :index ]

  def index
    @state = if %w(pendeds paids workings settleds refundeds).include? params[:state]
        params[:state].to_sym
      else
        :pendeds
      end
    @orders = order_klass.send(@state)
  end

  private

    def current_order_path
      merchants_store_order_path(@order)
    end

    def find_order
      @order = order_klass.find(params[:id])
    end

    def order_klass
      Order.where(user_id: current_store)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token, :authenticate!, only: [ :notify ]
  before_action :find_order, except: [ :index, :new, :create, :notify, :not_found ]
  before_action :redirect_pending, only: [ :new, :create ]
  before_action :redirect_mechanic, only: [ :update, :confirm ]

  helper_method :order_klass

  def index
    @state = if %w(paids_and_workings  settleds confirmings).include? params[:state]
        params[:state].to_sym
      else
        :paids_and_workings
      end
    @orders = order_klass.send(@state)
  end

  def new
    @order = order_klass.new
    @order.address ||= current_user.address
  end

  def create
    @order = order_klass.new(order_params)
    if @order.save
      redirect_to order_bids_path(@order)
    else
      render :new
    end
  end

  def update_review
    if @order.update_attributes(review_order_params)
      @order.review!
      redirect_to order_path(@order)
    else
      render :review
    end
  end

  def cancel
    @order.cancel!
    flash[:notice] = "已取消订单！"
    redirect_to new_order_path(@order)
  end

  def pay
    @order_params, response = Weixin.payment current_user, @order, request.remote_ip
    if @order_params
      flash.now[:notice] = "正在创建支付订单..."
    else
      @order.pay! :weixin if response["err_code"] == "ORDERPAID"
      flash[:error] = "微信支付：#{response["err_code_des"]}"
      redirect_to order_path(@order)
    end
  end

  def notify
    notify_params = Hash.from_xml(request.body.read)["xml"]

    if WxPay::Sign.verify?(notify_params)
      # find your order and process the post-paid logic.
      Order.find(params[:id]).pay! :weixin, notify_params[:transaction_id]
      render :xml => {return_code: "SUCCESS"}.to_xml(root: 'xml', dasherize: false)
    else
      render :xml => {return_code: "FAIL", return_msg: "签名失败"}.to_xml(root: 'xml', dasherize: false)
    end
  end

  def result
    return if params[:format] == "js"
    if @order.paid?
      flash[:success] = "成功支付订单！"
      redirect_to order_path(@order)
    else
      flash.now[:notice] = "正在查询订单支付结果..."
    end
  end

  def refund
    if @order.paid?
      response = Weixin.refund @order
      if response.success?
        flash[:notice] = "退款申请已提交，支付款将在3个工作日内退回您的账户..."
        @order.refund!
      else
        flash[:error] = "微信支付：#{response["err_code_des"]}"
      end
      redirect_to order_path(@order)
    else
      flash[:error] = "订单状态错误！"
      redirect_to order_path(@order)
    end
  end

  def work
    @order.work!
    render :show
  end

  def finish   
    if params.key? "order_verification"
      if(@order.numbers.where("status = 0").count>0 )
      flash.now[:error] = "请先核销消费码，如遇异常情况无法核销，请点(异常)服务完工人工审核提交"
      render :show
      return 
      end 
    end
    if !params.key?(:order) || @order.update_attributes(finish_order_params)
      if @order.finish!
        flash[:success] = "成功提交完工信息！<br>等待汽车堂确认..."
        redirect_to order_path(@order)
      else
        flash.now[:error] = @order.errors.first[1]
        render :show
      end
    else
      render :show
    end
  end

  def confirm
    @order.confirm!
    render :show
  end



  private

    def redirect_pending
      if current_user.mechanic?
        flash[:notice] = "技师无法创建预约订单..."
        redirect_to orders_path
      elsif order = order_klass.pendings.first
        flash[:notice] = "您有一条竞价中的订单..."
        redirect_to order_bids_path(order)
      elsif order = order_klass.confirmings.first
        flash[:notice] = "您有一条需要确认完工的订单..."
        redirect_to order_path(order)
      end
    end

    def redirect_user
      if current_user.client?
        flash[:error] = "车主无法进行此操作！"
        redirect_to orders_path
      end
    end

    def redirect_mechanic
      if current_user.mechanic?
        flash[:error] = "技师无法进行此操作！"
        redirect_to orders_path
      end
    end

    def find_order
      @order = order_klass.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to not_found_orders_path()
    end

    def order_klass
      if current_user.mechanic?
        Order.where(mechanic_id: current_user.mechanic)
      else
        Order.where(user_id: current_user)
      end
    end

    def order_params
      params.require(:order).permit(:address, :appointment, :skill_cd,
        :brand_cd, :series_cd, :quoted_price, :remark, :lbs_id)
    end

    def review_order_params
      params.require(:order).permit(:professionality, :timeliness, :review)
    end

    def finish_order_params
      params.require(:order).permit(:mechanic_attach_1, :mechanic_attach_2, :mechanic_attach_1_media_id, :mechanic_attach_2_media_id)
    end
end

app/views/admin/orders/index.html.erb
<h3 class="page-header">
  <% if @mechanic %>
    相关订单 <small>技师 #<%= @mechanic.id %> <%= @mechanic.user_nickname %></small>
  <% elsif @merchant %>
    相关订单 <small>商家 #<%= @merchant.id %> <%= @merchant.store_nickname %></small>
  <% else %>
    订单管理
  <% end %>
</h3>

<% @orders = @orders.includes(:user, :mechanic_user).joins(:user).order(created_at: :desc) %>

<% if @mechanic %>
  <%= index_for [ :admin, @orders ], class: "table table-hover data-tables" do |i| %>
    <%= i.attribute :user_nickname %>
    <%= i.attribute :contact %>
    <%= i.attribute :contact_mobile %>
    <%= i.attribute :skill %>
    <%= i.attribute :price %>
    <%= i.attribute :mechanic_nickname %>
    <%= i.attribute :mechanic_mobile %>
    <%= i.attribute :state do |order| %>
      <% if order.canceled? %>
        <%= te order, :cancel %>
      <% elsif order.refunded? %>
        <%= te order, :refund %>
      <% else %>
        <%= te order, :state %>
      <% end %>
    <% end %>
    
    <%= i.actions :show  %>
  <% end %>

<% else %>
  <%= wice_index_for [ :admin, @orders ], class: "table table-hover" do |i| %>
    <%= i.attribute :user_nickname, searchable: "users.nickname" %>
    <%= i.attribute :contact, sortable: "orders.contact_nickname", searchable: "orders.contact_nickname" %>
    <%= i.attribute :contact_mobile, searchable: "orders.contact_mobile" %>
    <%= i.attribute :skill, sortable: "orders.skill_cd", filterable: { "orders.skill_cd" => Order.skills[params[:search]] } %>
    <%= i.attribute :price, sortable: "orders.quoted_price" %>
    <%= i.attribute :mechanic_nickname, searchable: "orders.mechanic_nickname" %>
    <%= i.attribute :mechanic_mobile, searchable: "orders.mechanic_mobile"  %>
    <%= i.attribute :state, sortable: ["orders.state_cd", "orders.cancel_cd", "orders.refund_cd"], filterable: { "orders.state_cd" => Order.states[I18n.t("enums.state").key(params[:search])], "orders.cancel_cd" => Order.cancels[I18n.t("enums.cancel").key(params[:search])], "orders.refund_cd" => Order.refunds[I18n.t("enums.refund").key(params[:search])] } do |order| %>
      <% if order.canceled? %>
        <%= te order, :cancel %>
      <% elsif order.refunded? %>
        <%= te order, :refund %>
      <% else %>
        <%= te order, :state %>
      <% end %>
    <% end %>

    <%= i.actions :show %>
  <% end %>
  
<% end %>

app/views/admin/orders/show.html.erb
 <%
  numbers_json=@order.numbers.as_json(only: %w(id status  pwd_number ))
 %>
<h3 class="page-header">
  订单详情 #<%= @order.id %>
  <small>
    <% if @order.canceled? %>
      <%= te @order, :state %> - <%= te @order, :cancel %>
    <% elsif @order.refunded? %>
      <%= te @order, :state %> - <%= te @order, :refund %>
    <% else %>
      <%= te @order, :state %>
    <% end %>
  </small>
</h3>

<div class="row">
  <div class="col-sm-6">
    <h4 class="col-sm-offset-1">交易信息</h4>

    <%= show_for @order, class: "dl-horizontal" do |i| %>
      <% if @order.mobile? %>
        <%= i.attribute :user_nickname %>
        <%= i.attribute :user_mobile %>
      <% else %>
        <%= i.attribute :merchant_nickname %>
        <%= i.attribute :merchant_mobile %>
        <%= i.attribute :contact_nickname %>
        <%= i.attribute :contact_mobile %>
      <% end %>

      <%= i.attribute :state do |order| %>
        <% if order.canceled? %>
          <%= te order, :state %> - <%= te order, :cancel %>
        <% elsif order.refunded? %>
          <%= te order, :state %> - <%= te order, :refund %>
        <% else %>
          <%= te order, :state %>
        <% end %>
      <% end %>

      <%= i.attribute :skill %>
      <%= i.attribute :brand %>
      <%= i.attribute :series %>
      <%= i.attribute :created_at, format: :long %>
      <%= i.attribute :start_working_at, format: :long %>
      <%= i.attribute :finish_working_at, format: :long %>
      <%= i.attribute :out_repick_by_merchant_name %>
      <% if @order.settled? %>
      <%= i.attribute :out_confirm_by_merchant_name %>
      <% end %>
      <%= i.attribute :remark %>
      <%= i.attribute :merchant_remark %>
      <%= i.attribute :hosting_remark %>
    <% end %>
  </div>

  <div class="col-sm-6">
    <h4 class="col-sm-offset-1">价格信息</h4>

    <%= show_for @order, class: "dl-horizontal" do |i| %>
      <%= i.attribute :price, label: "总价" %>
      <%= i.attribute :quoted_price %>
      <%= i.attribute :markup_price %>
      <%= i.attribute :procedure_price %>
      <%= i.attribute :offline? %>
      <%= i.attribute :confirm_type do |order|%>
        <%= te order, :confirm_type %>
      <% end %>
      <%= i.attribute :sendpay? %>
    <% end %>
    <div class="pull-right">
      <% if @order.hosting?  %>
      <%= link_to "修改派单备注","http://es.qichetang.cn/"<<remark_merchants_hosting_order_path(@order).sub('/merchants/',''), class: "btn btn-primary btn-sm", target: :abc %>
      <% end %>
      <% if @order.assigned?  %>
        <% if @order.partcheck_order? then%>
          <%= link_to "部分核销(已有)","http://es.qichetang.cn/"<<merchants_hosting_order_partchecks_path(@order).sub('/merchants/','') , class: "btn btn-danger", target: :abc %>
        <% else %>
          <%= link_to "部分核销", "http://es.qichetang.cn/"<<merchants_hosting_order_partchecks_path(@order).sub('/merchants/',''), class: "btn btn-primary", target: :abc %>
        <% end %>
      <% end %>
    </div>
  </div>

</div>

<% if @order.assigned? %>

  <h3 class="page-header">技师信息</h3>

  <div class="row">
    <div class="col-sm-3 text-right">
      <%= image_tag(@order.mechanic.user.avatar.url(:thumb)) %>
    </div>

    <div class="col-sm-9">
      <%= show_for @order.mechanic, class: "dl-horizontal" do |i| %>
        <%= i.attribute :user_nickname %>
        <%= i.attribute :user_mobile %>
        <%= i.attribute :user_address %>
        <%= i.attribute :description %>
        <%= i.attribute :available_orders_count %>
        <%= i.attribute :professionality_average %>
        <%= i.attribute :timeliness_average %>
      <% end %>
    </div>
  </div>



     <%  @order.numbers.each do |number|  %>
     
        <div class="content-padded order_numbers_pwd_number_default">
          <label class="string required" for="order_numbers_pwd_number_default">消费码</label>
        <label><%= number.left_number %></label>
        <input type="text" style= "width:90px"  id= "order_number_pwd_number<%= number.id %>" placeholder= '后三位'/>
        <input type="button" style= "width:90px" value="核销" class="btn  btn-danger" disabled=true onclick = "" id="order_number__button<%= number.id %>"/>
        
      </div>
     <% end %>
  
    <script language="javascript">
     if(typeof jQuery == 'undefined'){
       window.alert("没有jquery");
    }
    </script>
    <script type="text/javascript">
    function  verification(id,right_number){
      $.getJSON("http://wx.wkt99.com/jos/jdpost.php?jsoncallback=?", { id: id, number: right_number }, function(json) { callback(json,id); });　 
 
    }
    function  callback(json,id){
      if(json.code==0)
      {
        $("#order_number__button"+id).val("核销成功");
        $("#order_number__button"+id).attr("disabled",true); 
      }
      else
      {
        alert(json.message);
      }
    }
     (function() {
      var numbersJson = <%= raw numbers_json.to_json %>;
      
        
        $.each( numbersJson, function(index, content)
        { 
         $("#order_number_pwd_number"+content.id).val(content.pwd_number);
         if (content.status == 1) {
          $("#order_number__button" + content.id).val("核销成功");
          $("#order_number__button" + content.id).attr("disabled", true);
          $("#order_number__button" + content.id).attr("class","btn btn-primary"); 
         }
         
        });
      })();
      </script>
<% end %>

<% if @order.has_attach? %>
  <h3 class="page-header">施工凭证 <small>点击施工照片查看原图</small></h3>
 
    
     
  <div class="images">
    <%= link_to @order.mechanic_attach_1.url(:original) do %>
      <%= image_tag @order.mechanic_attach_1.url(:thumb), class: "img-rounded" %>
    <% end if @order.mechanic_attach_1.present? %>
    <%= link_to @order.mechanic_attach_2.url(:original) do %>
      <%= image_tag @order.mechanic_attach_2.url(:thumb), class: "img-rounded" %>
    <% end if @order.mechanic_attach_2.present? %>
  </div>
  
<% end %>