config/routes.rb
Rails.application.routes.draw do

  options = Rails.env.production? ? { path: "", constraints: { subdomain: 'es' }} : {}

  concern :pick do
    member do
      get :pick
      patch :pick, action: :update_pick
    end
  end

  concern :review do
    member do
      get :review
      patch :review, action: :update_review
    end
  end

  namespace :merchants, options do
    resource :merchant_session, path: "session"
    resource :merchant do
      get :forget_password
      match :verification_code, via: [:get, :post, :patch]
      match :confirm, via: [:post, :patch]

      get :password
      patch :password, action: :update_password
    end

    resource :note

    resources :orders, concerns: [:pick, :review] do
      resources :bids do
        member do
          get :pick
        end
      end

      resources :numbers

      collection do
        get :"pay/:id", action: :pay, as: :pay
      end

      member do
        post :pend
        post :cancel
        match :refund, via: [:get, :patch]
        match :notify, via: [:get, :post]
        get :result
        post :confirm
        post :rework
        get :revoke
        get :remark
        patch :remark, action: :update_remark
      end
    end

    namespace :hosting do
      resources :orders, concerns: [:pick, :review] do
        resources :partchecks
        member do
          match :refund, via: [:get, :patch]
          post :confirm
          post :rework
          get :revoke
          get :remark
          patch :remark, action: :update_remark
          get :procedure_price
          patch :procedure_price, action: :update_procedure_price
          get :emergency
          get :unemergency
          post :confirmwithdrawal
          get :service_staff
        end
        collection do
          get 'automatic'
          get 'automatic_pop'
        end
      end
      resources :numbers
      resources :partchecks
    end

    resources :merchants
    resources :mechanics do
      member do
        post :follow
        post :unfollow
        get :remark
        patch :remark, action: :update_remark
        get :reviews
        get :"skills/:skill", action: :skill, as: :skill
      end
    end

    namespace :admin do
      resources :merchants do
        member do
          post :active
          post :inactive
        end
      end
      resources :orders do
        member do
          post :close
        end
      end
      resource :store
      resources :recharges do
        member do
          match :notify, via: [:get, :post]
          get :result
        end
      end
    end

    namespace :store do
      resources :orders
    end
    resource :store

    root to: "orders#new"
  end

  mount WeixinRailsMiddleware::Engine, at: "/"
  resource :user do
      member do
        get :photo
        patch :update_photo
        get :holiday
        patch :update_holiday
      end
    end
  resource :user_session, path: "session" do
    post :verification_code
  end
  resource :user_group do
    get :weixin_qr_code
    get :users
  end
  resources :mechanics do
    member do
      get :follow
      get :unfollow
      get :reviews
    end
  end

  resources :orders, concerns: [:review] do
    resources :bids do
      member do
        get :pick
      end
    end

    collection do
      get :"pay/:id", action: :pay, as: :pay
      get :not_found
    end

    member do
      get :cancel
      get :refund
      post :notify
      get :result
      get :work
      patch :finish
      get :confirm
    end
  end

  resources :withdrawals

  namespace :admin do
    concern :confirm do
      collection do
        get :confirmed
      end
      member do
        post :confirm
      end
    end
    concern :confirm_nopay do
      collection do
        get :confirm_nopayed
      end
      member do
        post :confirm_nopay
      end
    end
    concern :message do
      member do
        post :message
      end
    end
    concern :cancel do
      collection do
        get :canceled
      end
      member do
        post :cancel
      end
    end
    concern :hide do
      collection do
        get :hidden
      end
      member do
        post :hide
        post :unhide
      end
    end
    concern :freeze do
      collection do
        get :frozen
      end
      member do
        post :freeze
      end
    end
    concern :hidereg do
      collection do
        get :reg
      end
      member do
        post :hidereg
      end
    end
    concern :hideupdate do
      collection do
        get :userupdate
      end
      member do
        post :hideupdate
      end
    end

    resource :administrator_session, path: "session"
    resource :administrator, only: [] do
      get :forget_password
      match :verification_code, via: [:get, :post, :patch]
      match :confirm, via: [:post, :patch]

      get :password
      patch :password, action: :update_password
    end

    resources :administrators do
      member do
        post :active
        post :inactive
      end
    end

    resources :users do
      member do
        post :mechanicize

        get :balance,:clear_weixin,:clear_withdrawal_weixin
        patch :balance, action: :update_balance
      end
    end
    resources :user_groups, concerns: [:confirm]
    resources :mechanics, concerns: [:hide,:hidereg,:hideupdate] do
      resources :orders
      resources :metrics
      collection do
        get :import
        post :import, action: :create_import
      end

      member do
        post :clientize
      end
    end
    resources :merchants, concerns: [:confirm] do
      resources :orders
      resources :metrics
      member do
        post :active
        post :inactive
        get :settings
        post :settings, action: :update_settings
        get :product
        patch :product, action: :update_product
      end
    end
    resources :orders
    resources :metrics
    resources :refunds, concerns: [:confirm, :freeze]
    resources :withdrawals, concerns: [:confirm, :cancel, :confirm_nopay, :message] do
      collection do
        get :settings
        post :settings, action: :update_settings
      end
    end
    namespace :settings do
      resources :skills
      resources :brands
      resources :series, except: :show
    end
    namespace :reports do
      resources :provinces
      resources :finishedprovinces
      resources :dayreports
      resources :profits
      resources :partchecks
    end

    root to: "users#index"
  end

  root to: "users#show"
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  before_action :find_order, except: [ :index ]

  def index
    @orders = if params[:mechanic_id]
        @mechanic = Mechanic.where(user_id: params[:mechanic_id]).first!
        @mechanic.orders
      elsif params[:merchant_id]
        @merchant = Merchant.where(user_id: params[:merchant_id]).first!
        @merchant.orders
      else
        Order.all
      end
  end

  private

    def find_order
      @order = Order.find(params[:id])
    end
end

app/controllers/merchants/admin/orders_controller.rb
class Merchants::Admin::OrdersController < Merchants::Admin::ApplicationController
  before_action :find_order, except: [ :index ]

  def index
    @state = if %w(pendeds paids workings settleds refundeds revieweds closeds).include? params[:state]
        params[:state].to_sym
      else
        :pendeds
      end
    @orders = order_klass.send(@state)
  end

  def close
    @order.close!
    flash[:notice] = "订单标记为已结算！"
    redirect_to current_order_path
  end

  private

    def current_order_path
      merchants_admin_order_path(@order)
    end

    def find_order
      @order = order_klass.find(params[:id])
    end

    def order_klass
      Order.where(user_id: current_store)
    end
end

app/controllers/merchants/hosting/numbers_controller.rb
class Merchants::Hosting::NumbersController < Merchants::ApplicationController
  #before_action :redirect_user_dispatcher
  def index
    @state = if %w(unchecked_numbers checked_numbers).include? params[:state]
        params[:state].to_sym
      else
        :unchecked_numbers
      end
    @numbers = Number.send(@state)
  end
  def checked?
    status && ["1", 1, true].include?(status)
  end
  
end

app/controllers/merchants/hosting/orders_controller.rb
class Merchants::Hosting::OrdersController < Merchants::OrdersController
  before_action :redirect_user
  before_action :redirect_user_dispatcher, only: [ :confirm, :confirmwithdrawal ]
  skip_before_action :redirect_user, only: [:automatic, :automatic_pop]
  skip_before_action :redirect_user_dispatcher, only: [:automatic, :automatic_pop]
  skip_before_action :authenticate!, only: [:automatic, :automatic_pop]
  before_action :find_order, except: [ :index, :new, :create, :notify, :not_found , :automatic, :automatic_pop]


  def index
    @state = if %w(unassigneds assigneds workings confirmings finisheds unfinisheds settleds emergencys finished_all_nochecks finished_part_nochecks unfinished_all_checks unfinished_part_checks).include? params[:state]
        params[:state].to_sym
      else
        :unassigneds
      end
    
    @orders = order_klass.send(@state)
  end
  


  def update_pick
    mechanic_id = params[:order][:mechanic_id]
    if mechanic_id.present?
      remark = params[:order][:remark]
      pre_remark = params[:order][:pre_remark]
      remark = pre_remark if pre_remark
      @order.update_attribute(:remark, remark) if remark
      procedure_price = params[:order][:pre_procedure_price]
      if(procedure_price.present?)
        if procedure_price.to_i > @order.quoted_price
        @order.errors.add(:pre_procedure_price, "应低于订单标价")
        render :show
        return 
        end
      end
      @order.update_attribute(:procedure_price, procedure_price) if procedure_price
      mechanic = Mechanic.find(mechanic_id)
      @order.repick! mechanic,current_merchant.id,current_merchant.nickname
      redirect_to current_order_path
    else
      @order.remark = params[:order][:remark]
      @order.errors.add :base, "请选择一个技师"
      render :pick
    end
  end

  def update_procedure_price
    if @order.update_attributes(procedure_price_order_params)
      redirect_to current_order_path
    else
      render :procedure_price
    end
  end

  def automatic
    Order.hostings.unassigneds.where("(skill_cd=28 or skill_cd=29 or skill_cd=42 or skill_cd=9 or skill_cd=34 or skill_cd=44 or skill_cd=146) and automatic_repick_check=false").each do |unassigned_order_klass|
       unassigned_order_klass_order=Order.find(unassigned_order_klass.id)
       unassigned_order_klass_order.automatic_repick!
       unassigned_order_klass_order.update_attribute(:automatic_repick_check,true)
    end 
    Order.hostings.confirmings.where("(hosting_remark is null or hosting_remark='') and automatic_confirm_check=false").each do |confirming_order_klass|
       confirming_order_klass_order=Order.find(confirming_order_klass.id)
       confirming_order_klass_order.automatic_confirm!
       confirming_order_klass_order.update_attribute(:automatic_confirm_check,true)
    end 
    #trigger automatic_repick
  end

  def automatic_pop
    Order.hostings.unassigneds.where("(skill_cd=28 or skill_cd=29 or skill_cd=42 or skill_cd=9 or skill_cd=34 or skill_cd=44 or skill_cd=146) and automatic_repick_check=false").each do |unassigned_order_klass|
       unassigned_order_klass_order=Order.find(unassigned_order_klass.id)
       unassigned_order_klass_order.automatic_repick!
    end 
  end  

  def service_staff
    @order.mechanic.update_attribute(:service_staff,params[:service_staff])
    flash[:notice] = "设置微信客服成功"
    redirect_to_referer!
  end

  private

    def current_order_path
      merchants_hosting_order_path(@order)
    end

    def redirect_pending
      ordercount = order_klass.confirmings.count
      if ordercount>0
        flash[:notice] = "您有#{ordercount}条需要确认完工的订单..."
        #redirect_to merchants_hosting_order_path(order)
      end
    end

    def order_klass
      Order.hostings
    end

    def find_order
      @order = order_klass.find(params[:id])
    end

    alias_method :find_store_order, :find_order

    def redirect_user
      unless current_store.host?
        flash[:error] = "无法访问此页面！"
        redirect_to merchants_root_path
      end
    end

    def remark_order_params
      params.require(:order).permit(:hosting_remark)
    end

    def procedure_price_order_params
      params.require(:order).permit(:procedure_price)
    end
end

app/controllers/merchants/hosting/partchecks_controller.rb
class Merchants::Hosting::PartchecksController < Merchants::ApplicationController
  before_action :redirect_user_dispatcher

  def index
    @order = Order.find(params[:order_id])
    @partchecks = @order.partchecks

    @partcheck = Partcheck.new
    @partcheck.set_default(@order) 
  end

  def create
    @partcheck = Partcheck.new(partcheck_params)
    @partcheck.confirm_by=current_merchant.id
    if @partcheck.save
      @order=Order.hostings.find(@partcheck.order_id)
      @order.update_attribute(:partcheck_order, true)
      redirect_to merchants_hosting_order_path(@order)
    else
      render :index
    end 
  end

  def partcheck_params
    params.require(:partcheck).permit(:order_id, :quoted_price, :quantity,
    :mechanic_income, :procedure_price, :remark, :confirm_type)
  end

end

app/controllers/merchants/store/orders_controller.rb
class Merchants::Store::OrdersController < Merchants::ApplicationController
  before_action :find_order, except: [ :index ]

  def index
    @state = if %w(pendeds paids workings settleds refundeds).include? params[:state]
        params[:state].to_sym
      else
        :pendeds
      end
    @orders = order_klass.send(@state)
  end

  private

    def current_order_path
      merchants_store_order_path(@order)
    end

    def find_order
      @order = order_klass.find(params[:id])
    end

    def order_klass
      Order.where(user_id: current_store)
    end
end

app/views/merchants/hosting/orders/automatic.html.erb
<h3 class="page-header">自动派单</h3>

app/views/merchants/hosting/orders/automatic_pop.html.erb
<h3 class="page-header">京东POP订单自动余额支付</h3>

app/views/merchants/hosting/orders/index.html.erb
<h3 class="page-header">托管订单</h3>

<%
  def order_state_link_to state, text
    link = link_to text, merchants_hosting_orders_path(state: state)
    class_name = (@state == state) ? "active" : ""
    %{<li class="#{class_name}">#{link}</li>}.html_safe
  end
  def number_state_link_to state, text
    link = link_to text, merchants_hosting_numbers_path(state: state)
    class_name = (@state == state) ? "active" : ""
    %{<li class="#{class_name}">#{link}</li>}.html_safe
  end
%>

<div class="row">
  <div class="col-md-2 col-xs-4">
    <ul class="nav nav-pills nav-stacked">
      <%= order_state_link_to :unassigneds, "未分配" %>
      <%= order_state_link_to :assigneds, "待服务" %>
      <%= order_state_link_to :workings, "服务中" %>
      <%= order_state_link_to :confirmings, "待确认完工" %>
      <%= order_state_link_to :finisheds, "待评价" %>
      <li class="divider"></li>
      <%= order_state_link_to :unfinisheds, "所有未完工" %>
      <%= order_state_link_to :settleds, "所有已完工" %>
      <li class="divider"></li>
      <%= order_state_link_to :emergencys, "紧急订单" %>
      <%= order_state_link_to :finished_all_nochecks, "完工全部未核销" %>
      <%= order_state_link_to :finished_part_nochecks, "完工部分未核销" %>
      <%= order_state_link_to :unfinished_all_checks, "未完工全部已核销" %>
      <%= order_state_link_to :unfinished_part_checks, "未完工部分已核销" %>
      
      <li class="divider"></li>
      <%= number_state_link_to :unchecked_numbers, "未核销消费码" %>
      <%= number_state_link_to :checked_numbers, "已核销消费码" %>
      
    </ul>
  </div>

  <%
   @order_field = (params[:order]||"")
    if(@order_field!="")
      @orders = @orders.includes(:store, :mechanic_user)
    else
      if(@state == :finished_all_nochecks || @state == :finished_part_nochecks)
        @orders = @orders.includes(:store, :mechanic_user).order(:finish_working_at) 
      else
        @orders = @orders.includes(:store, :mechanic_user).order(:appointment) 
      end
    end
   %>

  <div class="col-md-10 col-xs-8">
  <% if  @state == :unfinisheds||@state == :settleds||@state == :assigneds||@state == :finisheds%>
    <%= wice_index_for [ :merchants, :hosting, @orders ], class: "table table-hover" do |i| %>
      <%= i.attribute :store_nickname, searchable: true  %>
      <%= i.attribute :contact_nickname,searchable: "orders.contact_nickname" %>
      <%= i.attribute :contact_mobile,searchable: "orders.contact_mobile" %>
      <%= i.attribute :appointment, format: :short %>
      <%= i.attribute :skill ,filterable: { "orders.skill_cd" => Order.skills[params[:search]] } %>
      <%= i.attribute :price %>
      <%= i.attribute :offline? %>
      <%= i.attribute :automatic %>
      <%= i.attribute :mechanic_nickname, searchable: true  %>
      <%= i.actions :show %>
    <% end %>
  <% else %>
   <%= index_for [ :merchants, :hosting, @orders ], class: "table table-hover data-tables" do |i| %>
      <%= i.attribute :store_nickname %>
      <%= i.attribute :contact_nickname %>
      <%= i.attribute :contact_mobile %>
      <%= i.attribute :appointment, format: :short %>
      <% if @state == :finished_all_nochecks || @state == :finished_part_nochecks %>
        <%= i.attribute :finish_working_at, format: :short %>
      <% end %>
      <%= i.attribute :skill  %>
      <%= i.attribute :price %>
      <%= i.attribute :offline? %>
      <%= i.attribute :mechanic_nickname %>
      <% if  @state == :finisheds %>
      <%= i.attribute :automatic_confirm? %>
      <% end %>
      <%= i.actions :show %>
    <% end %>
    <script type="text/javascript">

      $(document).ready(function() {
          $('#orders').DataTable( {
              "bStateSave": true,
              "pagingType": "full_numbers",
                'fnDrawCallback': function(table) {    
                    $("#orders_paginate").append("   <input type='text' id='changePage' class='form-control input pagination' style='margin-top:0px;width:50px;height:27px'> ");    
                    var oTable = $("#orders").dataTable();    
                    $('#changePage').keypress(function(e) {  
                        if (e.which === 13 || e.keyCode === 13) {  
                          if($("#changePage").val() && $("#changePage").val() > 0) {    
                              var redirectpage = $("#changePage").val() - 1;    
                          } else {    
                              var redirectpage = 0;    
                          }    
                          oTable.fnPageChange(redirectpage);  
                        }  
                    });    
                }
          } );
      } );

    </script>
  <% end %>
  </div>
</div>

app/views/merchants/hosting/orders/pick.html.erb
<ul class="nav nav-tabs page-header">
  <li><h3><%= @order.assigned? ? "改派技师" : "指派技师" %></h3></li>
  <li class="active"><a href="#table_tab" data-toggle="tab">列表</a></li>
  <li><a href="#map_tab" data-toggle="tab">地图</a></li>
</ul>

<%= bootstrap_simple_form_for([ :merchants, :hosting, @order ], url: pick_merchants_hosting_order_path(@order)) do |f| %>
  <div class="row">
    <%= render partial: "shared/orders/pick_list", locals: { f: f } %>

    <div class="col-md-7">
      <%= f.input :remark, hint: "备注对所有人可见", input_html: { rows: 4 } %>
    </div>

    <div class="col-md-12">
      <%= f.button :submit, "确定", class: "btn-primary pull-right" %>
    </div>
  </div>
<% end %>

<%= render partial: "shared/orders/pick_script" %>

app/views/merchants/hosting/orders/procedure_price.html.erb
<h3 class="page-header">手续费 <small>手续费应低于订单标价：1元</small></h3>

<div class="row">
  <div class="col-md-7">
    <%= bootstrap_simple_form_for([ :merchants, @order ], url: procedure_price_merchants_hosting_order_path(@order)) do |f| %>
      <%= f.error_messages %>

      <%= f.input :procedure_price %>

      <%= f.button :submit, "确定", class: "btn-primary pull-right" %>
    <% end %>
  </div>
</div>

app/views/merchants/hosting/orders/remark.html.erb
<h3 class="page-header">派单备注</h3>

<div class="row">
  <div class="col-md-7">
    <%= bootstrap_simple_form_for([ :merchants, @order ], url: remark_merchants_hosting_order_path(@order)) do |f| %>
      <%= f.error_messages %>

      <%= f.input :hosting_remark, input_html: { rows: 4 } %>

      <%= f.button :submit, "确定", class: "btn-primary pull-right" %>
    <% end %>
  </div>
</div>

app/views/merchants/hosting/orders/review.html.erb
<h3 class="page-header">点评技师</h3>

<div class="row">
  <div class="col-md-7">
    <%= bootstrap_simple_form_for([ :merchants, @order ], url: review_merchants_hosting_order_path(@order)) do |f| %>
      <%= f.error_messages %>

      <%= f.input :professionality do %>
        <div class="stars">
          <%= bootstrap_icon_stars @order.professionality %>
          <%= f.hidden_field :professionality %>
        </div>
      <% end %>
      <%= f.input :timeliness do %>
        <div class="stars">
          <%= bootstrap_icon_stars @order.timeliness %>
          <%= f.hidden_field :timeliness %>
        </div>
      <% end %>
      <%= f.input :review, input_html: { rows: 4 } %>

      <%= f.button :submit, "确定", class: "btn-primary pull-right" %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  (function() {
    var $elements = $(".stars .glyphicon");
    $elements.click(function() {
      var $parent = $(this).parent();
      var $icons = $parent.find(".glyphicon");
      var $hiddenInput = $parent.find("input[type=hidden]");
      var value = $icons.index(this) + 1;

      $hiddenInput.val(value);
      $icons.slice(0, value).removeClass("glyphicon-star-empty").addClass("glyphicon-star");
      $icons.slice(value, $icons.length).removeClass("glyphicon-star").addClass("glyphicon-star-empty");
    });
  })();
</script>